import React, { useEffect } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import {
  FaArrowRight,
  FaArrowLeft,
  FaCheckCircle,
  FaShieldAlt,
  FaClock,
  FaUsers,
  FaStar,
  FaDownload,
} from "react-icons/fa";
import frameworkData from "../data/frameworkData";

export default function FrameworkCard() {
  const { slug } = useParams();
  const navigate = useNavigate();

  const framework = frameworkData.find((f) => f.slug === slug);

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, [slug]);

  if (!framework) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center text-center px-6">
        <FaShieldAlt className="text-5xl text-slate-300 mb-6" />
        <h1 className="text-2xl font-bold text-slate-800 mb-2">Framework Not Found</h1>
        <p className="text-slate-500 mb-8">
          We couldn't find a framework matching <code className="bg-slate-100 px-2 py-0.5 rounded text-sm">{slug}</code>.
        </p>
        <Link
          to="/frameworks"
          className="inline-flex items-center gap-2 text-sm font-semibold text-white px-6 py-3 rounded-full hover:opacity-90 transition"
          style={{ background: "#155DFC" }}
        >
          <FaArrowLeft className="text-xs" /> Back to Frameworks
        </Link>
      </div>
    );
  }

  const relatedFrameworks = frameworkData.filter((f) =>
    framework.relatedFrameworks.includes(f.slug)
  );

  const handleDownloadBrochure = () => {
    const content = `======================================================================
${framework.name.toUpperCase()} COMPLIANCE BROCHURE
======================================================================

Category: ${framework.category}
Estimated Timeline: ${framework.estimatedTimeline}
Total Compliance Controls: ${framework.controls}

----------------------------------------------------------------------
OVERVIEW & CONTEXT
----------------------------------------------------------------------
${framework.overview}

----------------------------------------------------------------------
WHY IT MATTERS
----------------------------------------------------------------------
${framework.whyImportant.map((item, idx) => `${idx + 1}. ${item}`).join('\n')}

----------------------------------------------------------------------
KEY COMPLIANCE REQUIREMENTS
----------------------------------------------------------------------
${framework.keyRequirements.map((item, idx) => `${idx + 1}. ${item.title}:
   ${item.description}`).join('\n\n')}

----------------------------------------------------------------------
BENEFITS OF IMPLEMENTATION
----------------------------------------------------------------------
${framework.benefits.map((item) => `- ${item}`).join('\n')}

----------------------------------------------------------------------
WHO SHOULD USE THIS FRAMEWORK
----------------------------------------------------------------------
${framework.whoShouldUse.map((item) => `- ${item}`).join('\n')}

----------------------------------------------------------------------
IMPLEMENTATION ROADMAP & STEPS
----------------------------------------------------------------------
${framework.implementationSteps.map((item, idx) => `${idx + 1}. ${item.title}:
   ${item.description}`).join('\n\n')}

======================================================================
Generated by Cryptus Compliance Platform
======================================================================`;

    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${framework.slug}-compliance-brochure.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen">

      {/* ── Hero ──────────────────────────────────────────────────── */}
      <section className="relative py-20 px-6 overflow-hidden">
        <div className="absolute -top-40 left-1/4 w-[500px] h-[400px] bg-indigo-400/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute -bottom-20 right-1/4 w-[400px] h-[300px] bg-violet-400/08 rounded-full blur-3xl pointer-events-none" />

        <div className="max-w-5xl mx-auto relative z-10 animate-fade-up">
          {/* Back link */}
          <button
            onClick={() => navigate("/frameworks")}
            className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-indigo-600 transition-colors mb-8 group"
          >
            <FaArrowLeft className="text-xs group-hover:-translate-x-1 transition-transform" />
            All Frameworks
          </button>

          <div className="flex flex-col md:flex-row gap-8 items-start">
            {/* Logo */}
            <div
              className={`w-24 h-24 rounded-3xl bg-gradient-to-br ${framework.color} flex items-center justify-center shrink-0 shadow-lg`}
            >
              <img
                src={framework.logo}
                alt={framework.name}
                className="w-14 h-14 object-contain"
              />
            </div>

            <div className="flex-1">
              <div className="flex flex-wrap items-center gap-3 mb-3">
                <span className="text-xs font-semibold px-3 py-1 rounded-full bg-indigo-50 text-indigo-600 border border-indigo-200">
                  {framework.category}
                </span>
                <Link
                  to={`/framework-card-controller/${framework.slug}`}
                  className="text-xs text-slate-400 hover:text-indigo-600 hover:underline transition-colors flex items-center gap-1 cursor-pointer"
                >
                  <FaShieldAlt className="text-[10px]" /> {framework.controls} controls
                </Link>
                <span className="text-xs text-slate-400 flex items-center gap-1">
                  <FaClock className="text-[10px]" /> {framework.estimatedTimeline}
                </span>
              </div>

              <h1 className="text-4xl md:text-5xl font-bold text-slate-900 leading-tight">
                {framework.name}
              </h1>

              <p className="mt-4 text-slate-500 text-base leading-relaxed max-w-2xl">
                {framework.shortDescription}
              </p>

              <div className="mt-8 flex flex-wrap gap-3">
                <Link
                  to="/register"
                  className="inline-flex items-center gap-2 text-sm font-semibold text-white px-6 py-3 rounded-full hover:opacity-90 hover:shadow-lg hover:shadow-indigo-300/40 transition-all"
                  style={{ background: "#155DFC" }}
                >
                  Get Started with {framework.name} <FaArrowRight className="text-xs" />
                </Link>
                <Link
                  to="/frameworks"
                  className="inline-flex items-center gap-2 text-sm font-semibold text-slate-700 px-6 py-3 rounded-full border border-slate-200 hover:border-indigo-300 hover:text-indigo-600 transition-all bg-white/60"
                >
                  View All Frameworks
                </Link>
                <button
                  onClick={handleDownloadBrochure}
                  className="inline-flex items-center gap-2 text-sm font-semibold text-slate-700 px-6 py-3 rounded-full border border-slate-200 hover:border-indigo-300 hover:text-indigo-600 transition-all bg-white/60 cursor-pointer shadow-sm"
                >
                  <FaDownload className="text-xs" /> Download Brochure
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Overview ──────────────────────────────────────────────── */}
      <section className="max-w-5xl mx-auto px-6 pb-16">
        <div className="bg-white/70 border border-white/80 rounded-3xl p-8 md:p-10 shadow-sm">
          <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-600 border border-indigo-200 mb-5">
            ✦ Overview
          </span>
          <h2 className="text-2xl md:text-3xl font-bold text-slate-900 mb-5">
            What is <span className="gradient-text">{framework.name}?</span>
          </h2>
          <p className="text-slate-600 leading-relaxed text-base">
            {framework.overview}
          </p>
        </div>
      </section>

      {/* ── Why It Matters ────────────────────────────────────────── */}
      <section className="max-w-5xl mx-auto px-6 pb-16">
        <div className="mb-8">
          <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-600 border border-indigo-200 mb-4">
            ✦ Why It Matters
          </span>
          <h2 className="text-2xl md:text-3xl font-bold text-slate-900">
            Why <span className="gradient-text">{framework.name}</span> Matters
          </h2>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {framework.whyImportant.map((reason, i) => (
            <div
              key={i}
              className="bg-white/70 border border-white/80 rounded-2xl p-6 shadow-sm card-hover flex gap-3"
            >
              <FaStar className="text-indigo-500 shrink-0 mt-0.5 text-sm" />
              <p className="text-sm text-slate-700 leading-relaxed">{reason}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Key Requirements ──────────────────────────────────────── */}
      <section className="max-w-5xl mx-auto px-6 pb-16">
        <div className="mb-8">
          <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-600 border border-indigo-200 mb-4">
            ✦ Key Requirements
          </span>
          <h2 className="text-2xl md:text-3xl font-bold text-slate-900">
            Core <span className="gradient-text">Requirements</span>
          </h2>
        </div>
        <div className="grid sm:grid-cols-2 gap-5">
          {framework.keyRequirements.map((req, i) => (
            <div
              key={i}
              className="bg-white/70 border border-white/80 rounded-2xl p-6 shadow-sm card-hover"
            >
              <div className="flex items-start gap-4">
                <span
                  className="w-9 h-9 rounded-xl flex items-center justify-center text-sm font-bold text-white shrink-0"
                  style={{ background: "#155DFC" }}
                >
                  {String(i + 1).padStart(2, "0")}
                </span>
                <div>
                  <h3 className="text-sm font-bold text-slate-900 mb-2">{req.title}</h3>
                  <p className="text-xs text-slate-500 leading-relaxed">{req.description}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Benefits & Who Should Use ──────────────────────────────── */}
      <section className="max-w-5xl mx-auto px-6 pb-16">
        <div className="grid md:grid-cols-2 gap-6">
          {/* Benefits */}
          <div className="bg-white/70 border border-white/80 rounded-3xl p-8 shadow-sm">
            <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-600 border border-indigo-200 mb-5">
              ✦ Benefits
            </span>
            <h2 className="text-xl font-bold text-slate-900 mb-6">
              Key <span className="gradient-text">Benefits</span>
            </h2>
            <ul className="space-y-3">
              {framework.benefits.map((benefit, i) => (
                <li key={i} className="flex items-start gap-3">
                  <FaCheckCircle className="text-indigo-500 shrink-0 mt-0.5 text-sm" />
                  <span className="text-sm text-slate-700 leading-relaxed">{benefit}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Who Should Use */}
          <div className="bg-white/70 border border-white/80 rounded-3xl p-8 shadow-sm">
            <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-600 border border-indigo-200 mb-5">
              ✦ Target Audience
            </span>
            <h2 className="text-xl font-bold text-slate-900 mb-6">
              Who Should <span className="gradient-text">Implement It?</span>
            </h2>
            <div className="flex flex-wrap gap-2">
              {framework.whoShouldUse.map((who, i) => (
                <span
                  key={i}
                  className="inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-full bg-slate-100 text-slate-600 border border-slate-200"
                >
                  <FaUsers className="text-[9px] text-indigo-400" />
                  {who}
                </span>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Implementation Steps ──────────────────────────────────── */}
      <section className="max-w-5xl mx-auto px-6 pb-16">
        <div className="mb-8">
          <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-600 border border-indigo-200 mb-4">
            ✦ Implementation
          </span>
          <h2 className="text-2xl md:text-3xl font-bold text-slate-900">
            Implementation <span className="gradient-text">Steps</span>
          </h2>
        </div>
        <div className="relative">
          {/* Vertical line */}
          <div className="absolute left-[22px] top-0 bottom-0 w-px bg-gradient-to-b from-indigo-200 via-indigo-100 to-transparent hidden sm:block" />
          <div className="space-y-4">
            {framework.implementationSteps.map((step, i) => (
              <div key={i} className="flex gap-5">
                {/* Step number */}
                <div
                  className="w-11 h-11 rounded-2xl flex items-center justify-center text-xs font-bold text-white shrink-0 relative z-10 shadow-md"
                  style={{ background: "#155DFC" }}
                >
                  {step.step}
                </div>
                <div className="bg-white/70 border border-white/80 rounded-2xl p-5 shadow-sm flex-1 card-hover">
                  <h3 className="text-sm font-bold text-slate-900 mb-1.5">{step.title}</h3>
                  <p className="text-xs text-slate-500 leading-relaxed">{step.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Certification & Timeline ───────────────────────────────── */}
      <section className="max-w-5xl mx-auto px-6 pb-16">
        <div className="grid sm:grid-cols-2 gap-5">
          {/* Certification Process */}
          <div className="bg-white/70 border border-white/80 rounded-3xl p-8 shadow-sm">
            <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-600 border border-indigo-200 mb-5">
              ✦ Certification
            </span>
            <h2 className="text-lg font-bold text-slate-900 mb-4">
              Certification <span className="gradient-text">Process</span>
            </h2>
            <p className="text-sm text-slate-600 leading-relaxed">
              {framework.certificationProcess}
            </p>
          </div>

          {/* Estimated Timeline */}
          <div
            className="rounded-3xl p-8 text-white relative overflow-hidden"
            style={{ background: "#155DFC" }}
          >
            <div className="absolute -top-10 -right-10 w-40 h-40 bg-white/10 rounded-full blur-2xl" />
            <div className="absolute -bottom-10 -left-10 w-40 h-40 bg-white/10 rounded-full blur-2xl" />
            <div className="relative z-10">
              <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold bg-white/20 text-white border border-white/30 mb-5">
                ✦ Timeline
              </span>
              <h2 className="text-lg font-bold mb-4">Estimated Timeline</h2>
              <div className="text-5xl font-black tracking-tight mb-3">
                {framework.estimatedTimeline}
              </div>
              <p className="text-blue-100 text-sm leading-relaxed">
                Timeline varies based on your organisation's size, existing security maturity, and available resources. Cryptus Compliance streamlines the process significantly.
              </p>
              <Link
                to="/register"
                className="mt-6 inline-flex items-center gap-2 bg-white text-indigo-600 font-semibold text-sm px-5 py-2.5 rounded-full hover:bg-indigo-50 transition"
              >
                Start Today <FaArrowRight className="text-xs" />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* ── Related Frameworks ────────────────────────────────────── */}
      {relatedFrameworks.length > 0 && (
        <section className="max-w-5xl mx-auto px-6 pb-16">
          <div className="mb-8">
            <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-600 border border-indigo-200 mb-4">
              ✦ Related
            </span>
            <h2 className="text-2xl md:text-3xl font-bold text-slate-900">
              Related <span className="gradient-text">Frameworks</span>
            </h2>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {relatedFrameworks.map((fw) => (
              <button
                key={fw.slug}
                onClick={() => navigate(`/framework-card/${fw.slug}`)}
                className="text-left bg-white/70 border border-white/80 rounded-3xl p-6 card-hover transition-all duration-200"
              >
                <div
                  className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${fw.color} flex items-center justify-center mb-4`}
                >
                  <img src={fw.logo} alt={fw.name} className="w-9 h-9 object-contain" />
                </div>
                <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-slate-100 text-slate-500">
                  {fw.category}
                </span>
                <h3 className="mt-3 text-base font-bold text-slate-900">{fw.name}</h3>
                <p className="mt-1.5 text-slate-500 text-xs line-clamp-2">{fw.shortDescription}</p>
                <div className="mt-3 flex items-center gap-1 text-xs font-medium text-indigo-600">
                  View Details <FaArrowRight className="text-[9px]" />
                </div>
              </button>
            ))}
          </div>
        </section>
      )}

      {/* ── CTA ───────────────────────────────────────────────────── */}
      <section className="max-w-5xl mx-auto px-6 pb-16">
        <div
          className="relative rounded-[32px] overflow-hidden p-12 text-center"
          style={{ background: "#155DFC" }}
        >
          <div className="absolute -top-20 -left-20 w-72 h-72 bg-white/10 rounded-full blur-3xl" />
          <div className="absolute -bottom-20 -right-20 w-72 h-72 bg-white/10 rounded-full blur-3xl" />
          <div className="relative z-10">
            <span className="inline-block px-4 py-1.5 rounded-full bg-white/10 text-white text-xs font-semibold border border-white/20 mb-6">
              ✦ Get Compliant Faster
            </span>
            <h2 className="text-2xl md:text-3xl font-bold text-white">
              Ready to achieve {framework.name} compliance?
            </h2>
            <p className="mt-4 text-blue-100 max-w-lg mx-auto text-sm leading-relaxed">
              Cryptus Compliance automates evidence collection, control tracking, and audit
              preparation — cutting your path to {framework.name} certification by up to 60%.
            </p>
            <div className="mt-8 flex flex-col sm:flex-row justify-center gap-4">
              <Link
                to="/book-demo"
                className="inline-flex items-center justify-center gap-2 bg-white text-indigo-600 font-semibold px-6 py-3 rounded-full hover:bg-indigo-50 transition"
              >
                Book Demo <FaArrowRight />
              </Link>
              <Link
                to="/frameworks"
                className="inline-flex items-center justify-center gap-2 border border-white/30 text-white font-semibold px-6 py-3 rounded-full hover:bg-white/10 transition"
              >
                Explore All Frameworks
              </Link>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
